# Generated by Django 4.2.1 on 2024-06-06 14:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("man", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="man",
            options={"ordering": ["-time_create"]},
        ),
        migrations.AddField(
            model_name="man",
            name="slug",
            field=models.SlugField(blank=True, default=" ", max_length=255),
        ),
        migrations.AddIndex(
            model_name="man",
            index=models.Index(
                fields=["-time_create"], name="man_man_time_cr_3b5135_idx"
            ),
        ),
    ]
