# Generated by Django 4.2.1 on 2024-06-06 16:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("man", "0003_alter_man_slug"),
    ]

    operations = [
        migrations.RenameField(
            model_name="man",
            old_name="is_publishe",
            new_name="is_published",
        ),
    ]
