# Generated by Django 4.2.1 on 2024-06-07 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("man", "0008_rename_is_publishe_man_is_published"),
    ]

    operations = [
        migrations.AlterField(
            model_name="man",
            name="cat",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.PROTECT,
                to="man.category",
            ),
        ),
    ]
