# Generated by Django 4.2.1 on 2024-06-10 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("man", "0010_tagpost_alter_man_cat_man_tags"),
    ]

    operations = [
        migrations.CreateModel(
            name="Wife",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("age", models.IntegerField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name="man",
            name="wife",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="zhena",
                to="man.wife",
            ),
        ),
    ]
