# Generated by Django 4.2.1 on 2024-06-22 09:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("man", "0011_wife_man_wife"),
    ]

    operations = [
        migrations.AddField(
            model_name="wife",
            name="m_count",
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
